# Change these first
owner: tbwcjw # Your GitHub organization or username, where this repository lives
repo: health.tbwcjw.online # The name of this repository

sites:
  - name: faucet.tbwcjw.online
    url: https://faucet.tbwcjw.online
  - name: HashCraft Faucet
    url: http://serverinspiron-ssh.dynv6.net:6436/
    maxResponseTime: 5000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: health.tbwcjw.online
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: health.tbwcjw.online
  introTitle: "Monitor the uptime of tbwcjw.online projects"
  introMessage: Using [upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: faucet
      href: https://faucet.tbwcjw.online
    - title: blog
      href: https://tbwcjw.online

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
